apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: authz-role
spec:
  rules:
  - services: ["backend.foo.svc.cluster.local"]
    methods: ["GET"]
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: authz-role-binding
spec:
  subjects:
  - properties:
      source.principal: "*"
      source.namespace: "test"
  roleRef:
    kind: ServiceRole
    name: "authz-role"
